
#include <sol/sol.hpp>
#include "engine/scripting/bindings/window_input_bindings.hpp"

namespace bubble
{
void CreateWindowInputBindings( sol::state& lua )
{
    lua["keyboard"] = lua.create_table_with(
        "UNKNOWN", KeyboardKey::UNKNOWN,
        "SPACE", KeyboardKey::SPACE,
        "APOSTROPHE", KeyboardKey::APOSTROPHE,
        "COMMA", KeyboardKey::COMMA,
        "MINUS", KeyboardKey::MINUS,
        "PERIOD", KeyboardKey::PERIOD,
        "SLASH", KeyboardKey::SLASH,
        "ZERO", KeyboardKey::ZERO,
        "ONE", KeyboardKey::ONE,
        "TWO", KeyboardKey::TWO,
        "THREE", KeyboardKey::THREE,
        "FOUR", KeyboardKey::FOUR,
        "FIVE", KeyboardKey::FIVE,
        "SIX", KeyboardKey::SIX,
        "SEVEN", KeyboardKey::SEVEN,
        "EIGHT", KeyboardKey::EIGHT,
        "NINE", KeyboardKey::NINE,
        "SEMICOLON", KeyboardKey::SEMICOLON,
        "EQUAL", KeyboardKey::EQUAL,
        "A", KeyboardKey::A,
        "B", KeyboardKey::B,
        "C", KeyboardKey::C,
        "D", KeyboardKey::D,
        "E", KeyboardKey::E,
        "F", KeyboardKey::F,
        "G", KeyboardKey::G,
        "H", KeyboardKey::H,
        "I", KeyboardKey::I,
        "J", KeyboardKey::J,
        "K", KeyboardKey::K,
        "L", KeyboardKey::L,
        "M", KeyboardKey::M,
        "N", KeyboardKey::N,
        "O", KeyboardKey::O,
        "P", KeyboardKey::P,
        "Q", KeyboardKey::Q,
        "R", KeyboardKey::R,
        "S", KeyboardKey::S,
        "T", KeyboardKey::T,
        "U", KeyboardKey::U,
        "V", KeyboardKey::V,
        "W", KeyboardKey::W,
        "X", KeyboardKey::X,
        "Y", KeyboardKey::Y,
        "Z", KeyboardKey::Z,
        "LEFT_BRACKET", KeyboardKey::LEFT_BRACKET,
        "BACKSLASH", KeyboardKey::BACKSLASH,
        "RIGHT_BRACKET", KeyboardKey::RIGHT_BRACKET,
        "GRAVE_ACCENT", KeyboardKey::GRAVE_ACCENT,
        "WORLD_1", KeyboardKey::WORLD_1,
        "WORLD_2", KeyboardKey::WORLD_2,

        /* Function keys */
        "ESCAPE", KeyboardKey::ESCAPE,
        "ENTER", KeyboardKey::ENTER,
        "TAB", KeyboardKey::TAB,
        "BACKSPACE", KeyboardKey::BACKSPACE,
        "INSERT", KeyboardKey::INSERT,
        "DEL", KeyboardKey::DEL,
        "RIGHT", KeyboardKey::RIGHT,
        "LEFT", KeyboardKey::LEFT,
        "DOWN", KeyboardKey::DOWN,
        "UP", KeyboardKey::UP,
        "PAGE_UP", KeyboardKey::PAGE_UP,
        "PAGE_DOWN", KeyboardKey::PAGE_DOWN,
        "HOME", KeyboardKey::HOME,
        "END", KeyboardKey::END,
        "CAPS_LOCK", KeyboardKey::CAPS_LOCK,
        "SCROLL_LOCK", KeyboardKey::SCROLL_LOCK,
        "NUM_LOCK", KeyboardKey::NUM_LOCK,
        "PRINT_SCREEN", KeyboardKey::PRINT_SCREEN,
        "PAUSE", KeyboardKey::PAUSE,
        "F1", KeyboardKey::F1,
        "F2", KeyboardKey::F2,
        "F3", KeyboardKey::F3,
        "F4", KeyboardKey::F4,
        "F5", KeyboardKey::F5,
        "F6", KeyboardKey::F6,
        "F7", KeyboardKey::F7,
        "F8", KeyboardKey::F8,
        "F9", KeyboardKey::F9,
        "F10", KeyboardKey::F10,
        "F11", KeyboardKey::F11,
        "F12", KeyboardKey::F12,
        "F13", KeyboardKey::F13,
        "F14", KeyboardKey::F14,
        "F15", KeyboardKey::F15,
        "F16", KeyboardKey::F16,
        "F17", KeyboardKey::F17,
        "F18", KeyboardKey::F18,
        "F19", KeyboardKey::F19,
        "F20", KeyboardKey::F20,
        "F21", KeyboardKey::F21,
        "F22", KeyboardKey::F22,
        "F23", KeyboardKey::F23,
        "F24", KeyboardKey::F24,
        "F25", KeyboardKey::F25,
        "KP_0", KeyboardKey::KP_0,
        "KP_1", KeyboardKey::KP_1,
        "KP_2", KeyboardKey::KP_2,
        "KP_3", KeyboardKey::KP_3,
        "KP_4", KeyboardKey::KP_4,
        "KP_5", KeyboardKey::KP_5,
        "KP_6", KeyboardKey::KP_6,
        "KP_7", KeyboardKey::KP_7,
        "KP_8", KeyboardKey::KP_8,
        "KP_9", KeyboardKey::KP_9,
        "KP_DECIMAL", KeyboardKey::KP_DECIMAL,
        "KP_DIVIDE", KeyboardKey::KP_DIVIDE,
        "KP_MULTIPLY", KeyboardKey::KP_MULTIPLY,
        "KP_SUBTRACT", KeyboardKey::KP_SUBTRACT,
        "KP_ADD", KeyboardKey::KP_ADD,
        "KP_ENTER", KeyboardKey::KP_ENTER,
        "KP_EQUAL", KeyboardKey::KP_EQUAL,
        "LEFT_SHIFT", KeyboardKey::LEFT_SHIFT,
        "LEFT_CONTROL", KeyboardKey::LEFT_CONTROL,
        "LEFT_ALT", KeyboardKey::LEFT_ALT,
        "LEFT_SUPER", KeyboardKey::LEFT_SUPER,
        "RIGHT_SHIFT", KeyboardKey::RIGHT_SHIFT,
        "RIGHT_CONTROL", KeyboardKey::RIGHT_CONTROL,
        "RIGHT_ALT", KeyboardKey::RIGHT_ALT,
        "RIGHT_SUPER", KeyboardKey::RIGHT_SUPER,
        "MENU", KeyboardKey::MENU
    );

    lua["mouse"] = lua.create_table_with(
        "UNKNOWN", MouseKey::UNKNOWN,
        "ONE", MouseKey::ONE,
        "TWO", MouseKey::TWO,
        "THREE", MouseKey::THREE,
        "FOUR", MouseKey::FOUR,
        "FIVE", MouseKey::FIVE,
        "SIX", MouseKey::SIX,
        "SEVEN", MouseKey::SEVEN,
        "EIGHT", MouseKey::EIGHT,
        "LAST", MouseKey::LAST,
        "LEFT", MouseKey::LEFT,
        "RIGHT", MouseKey::RIGHT,
        "MIDDLE", MouseKey::MIDDLE
    );

}

}


